version: '2'

services:

    nginx:
      restart: always
      image: nginx

    database:
      restart: always
      image: postgres:9.5
      expose:
        - 5432
      volumes:
        - ./postgres/data:/var/lib/postgresql

    backend:
      restart: always
      build:
        context: .
        dockerfile: ./docker/compose/django/Dockerfile
      volumes:
        - .:/app

    frontend:
      restart: always
      build:
        context: .
        dockerfile: ./docker/compose/web/Dockerfile
      volumes:
        - .:/app
